#!/usr/bin/env python3
"""
ChromaDB Embedding Pipeline for NASA Space Mission Data - Text Files Only

This script reads parsed text data from various NASA space mission folders and creates
a permanent ChromaDB collection with OpenAI embeddings for RAG applications.
Optimized to process only text files to avoid duplication with JSON versions.

Supported data sources:
- Apollo 11 extracted data (text files only)
- Apollo 13 extracted data (text files only)
- Apollo 11 Textract extracted data (text files only)
- Challenger transcribed audio data (text files only)
"""

import argparse
import hashlib
import logging
import time
from datetime import datetime
from pathlib import Path
from typing import Any, Callable, Dict, List, Literal, Set, Tuple

import chromadb
from chromadb.api.models import Collection as chromadb_collection
from chromadb.api import ClientAPI
from tqdm import tqdm

from openai import OpenAI

from src.rag_types import (
    CollectionInfo,
    CollectionStats,
    DocumentUpdateStats,
    Metadata,
    PipelineStats,
    RetrievalResult,
    normalize_retrieval_result,
)

UpdateMode = Literal["skip", "update", "replace"]

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler('chroma_embedding_text_only.log'),
        logging.StreamHandler()
    ]
)
# Disable the logs generated by OpenAI client when sending requests to the embeddingendponit. #
#  There can be thousands and make the logs hard to read
logging.getLogger("httpx").setLevel(logging.WARNING) 
logger = logging.getLogger(__name__)

class ChromaEmbeddingPipelineTextOnly:
    """Pipeline for creating ChromaDB collections with OpenAI embeddings - Text files only"""

    openai_api_key: str
    chroma_persist_directory: str
    collection_name: str
    embedding_model: str
    chunk_size: int
    chunk_overlap: int
    openai_base_url: str | None
    openai_client: OpenAI
    chroma_client: ClientAPI
    collection: chromadb_collection.Collection
    
    def __init__(self, 
                 openai_api_key: str,
                 chroma_persist_directory: str = "./chroma_db",
                 collection_name: str = "nasa_space_missions_text",
                 embedding_model: str = "text-embedding-3-small",
                 chunk_size: int = 1000,
                 chunk_overlap: int = 200,
                 openai_base_url: str | None = None,
                 openai_embedding_model: str | None = None) -> None:
        """
        Initialize the embedding pipeline
        
        Args:
            openai_api_key: OpenAI API key
            chroma_persist_directory: Directory to persist ChromaDB
            collection_name: Name of the ChromaDB collection
            embedding_model: OpenAI embedding model to use
            chunk_size: Maximum size of text chunks
            chunk_overlap: Overlap between chunks
            openai_base_url: Optional base URL for the OpenAI-compatible API
            openai_embedding_model: Optional OpenAI embedding model override
        """
        if (
            isinstance(chunk_size, bool)
            or not isinstance(chunk_size, int)
            or chunk_size <= 0
        ):
            raise ValueError("chunk_size must be a positive integer")
        if (
            isinstance(chunk_overlap, bool)
            or not isinstance(chunk_overlap, int)
            or chunk_overlap < 0
            or chunk_overlap >= chunk_size
        ):
            raise ValueError(
                "chunk_overlap must be non-negative and less than chunk_size"
            )

        self.openai_api_key = openai_api_key
        self.chroma_persist_directory = chroma_persist_directory
        self.collection_name = collection_name
        selected_embedding_model = (
            openai_embedding_model
            if openai_embedding_model is not None
            else embedding_model
        )
        self.embedding_model = selected_embedding_model
        self.chunk_size = chunk_size
        self.chunk_overlap = chunk_overlap
        self.openai_base_url = openai_base_url
        client_options: Dict[str, Any] = {}
        if openai_base_url:
            client_options["base_url"] = openai_base_url
        self.openai_client = OpenAI(api_key=openai_api_key, **client_options)
        self.chroma_client = chromadb.PersistentClient(path=chroma_persist_directory)
        self.collection = self.chroma_client.get_or_create_collection(
            name=collection_name,
            metadata={"embedding_model": selected_embedding_model},
        )
        collection_metadata = dict(self.collection.metadata or {})
        existing_embedding_model = collection_metadata.get("embedding_model")
        if (
            existing_embedding_model
            and existing_embedding_model != selected_embedding_model
        ):
            raise ValueError(
                "The existing collection uses embedding model "
                f"{existing_embedding_model!r}, not {selected_embedding_model!r}. "
                "Use a new collection or rebuild its vectors."
            )
        if existing_embedding_model is None:
            if self.collection.count() > 0:
                raise ValueError(
                    "Cannot safely assign an embedding model to a populated "
                    "collection with unknown embedding model provenance."
                )
            collection_metadata["embedding_model"] = selected_embedding_model
            self.collection.modify(metadata=collection_metadata)
    
    def chunk_text(self, text: str, metadata: Metadata) -> List[Tuple[str, Metadata]]:
        """
        Split text into chunks with metadata
        
        Args:
            text: Text to chunk
            metadata: Base metadata for the text
            
        Returns:
            List of (chunk_text, chunk_metadata) tuples
        """
        if not text or not text.strip():
            return []

        chunks: List[Tuple[str, Metadata]] = []
        start = 0
        while start < len(text):
            end = min(start + self.chunk_size, len(text))
            if end < len(text):
                boundary = max(
                    text.rfind(". ", start, end),
                    text.rfind("! ", start, end),
                    text.rfind("? ", start, end),
                    text.rfind("\n", start, end),
                )
                if boundary >= start + self.chunk_size // 2:
                    end = boundary + 1

            chunk = text[start:end]
            if chunk:
                chunk_metadata = dict(metadata)
                chunk_metadata["chunk_index"] = len(chunks)
                chunks.append((chunk, chunk_metadata))
            if end == len(text):
                break
            start = max(start + 1, end - self.chunk_overlap)
        return chunks
    
    def check_document_exists(self, doc_id: str) -> bool:
        """
        Check if a document with the given ID already exists in the collection
        
        Args:
            doc_id: Document ID to check
            
        Returns:
            True if document exists, False otherwise
        """
        result = self.collection.get(ids=[doc_id], include=[])
        return bool(result.get("ids"))
    
    def update_document(self, doc_id: str, text: str, metadata: Metadata) -> bool:
        """
        Update an existing document in the collection
        
        Args:
            doc_id: Document ID to update
            text: New text content
            metadata: New metadata
            
        Returns:
            True if successful, False otherwise
        """
        embedding = self.get_embedding(text)
        self.collection.update(
            ids=[doc_id],
            documents=[text],
            metadatas=[metadata],
            embeddings=[embedding],
        )
        logger.debug("Updated document: %s", doc_id)
        return True
    
    def delete_documents_by_source(self, source_pattern: str) -> int:
        """
        Delete all documents from a specific source (useful for re-processing files)
        
        Args:
            source_pattern: Pattern to match source names
            
        Returns:
            Number of documents deleted
        """
        # Get all documents
        all_docs = self.collection.get(include=["metadatas"])

        # Find documents matching the source pattern
        ids_to_delete: List[str] = []
        if all_docs["metadatas"]:
            for i, metadata in enumerate(all_docs["metadatas"]):
                if isinstance(metadata["source"], str) and source_pattern in metadata["source"]:
                    ids_to_delete.append(all_docs["ids"][i])

        if ids_to_delete:
            self.collection.delete(ids=ids_to_delete)
        logger.info(
            "Deleted %s documents matching source pattern: %s",
            len(ids_to_delete),
            source_pattern,
        )
        return len(ids_to_delete)
    
    def get_file_documents(self, file_path: Path) -> List[str]:
        """
        Get all document IDs for a specific file
        
        Args:
            file_path: Path to the file
            
        Returns:
            List of document IDs for the file
        """
        source = file_path.stem
        mission = self.extract_mission_from_path(file_path)
            
        # Get all documents
        all_docs = self.collection.get(include=["metadatas"])
            
        # Find documents from this file
        requested_path = file_path.resolve()
        matching_ids: List[str] = []
        for doc_id, metadata in zip(all_docs["ids"], all_docs["metadatas"] if all_docs["metadatas"] else []):
            if metadata.get("mission") != mission:
                continue
            stored_path = metadata.get("file_path")
            if stored_path:
                if Path(str(stored_path)).resolve() == requested_path:
                    matching_ids.append(doc_id)
            elif metadata.get("source") == source:
                matching_ids.append(doc_id)
        return matching_ids
    
    def get_embedding(self, text: str) -> List[float]:
        """
        Get OpenAI embedding for text
        
        Args:
            text: Text to embed
            
        Returns:
            Embedding vector
        """
        if not text or not text.strip():
            raise ValueError("text must be non-empty to create an embedding")
        response = self.openai_client.embeddings.create(
            model=self.embedding_model,
            input=text,
        )
        try:
            embedding = response.data[0].embedding
        except (AttributeError, IndexError, TypeError) as error:
            raise ValueError("OpenAI returned a malformed embedding response") from error
        return embedding

    def generate_document_id(self, file_path: Path, metadata: Metadata) -> str:
        """
        Generate stable document ID based on file path and chunk position
        This allows for document updates without changing IDs
        """
        mission = str(metadata.get("mission") or self.extract_mission_from_path(file_path))
        source = str(metadata.get("source") or file_path.stem)
        chunk_index = int(metadata.get("chunk_index", 0))

        def normalize(value: str) -> str:
            return "".join(
                character if character.isalnum() or character in "-_" else "_"
                for character in value.lower()
            ).strip("_")

        canonical_path = str(file_path.resolve())
        path_digest = hashlib.sha256(canonical_path.encode("utf-8")).hexdigest()[:8]
        return (
            f"{normalize(mission)}_{normalize(source)}_{path_digest}_"
            f"chunk_{chunk_index:04d}"
        )
    
    def process_text_file(self, file_path: Path) -> List[Tuple[str, Metadata]]:
        """
        Process plain text files with enhanced metadata extraction
        
        Args:
            file_path: Path to text file
            
        Returns:
            List of (text, metadata) tuples
        """
        with open(file_path, "r", encoding="utf-8") as source_file:
            content = source_file.read()

        if not content.strip():
            return []

        metadata: Metadata = {
            "source": file_path.stem,
            "file_path": str(file_path.resolve()),
            "file_type": "text",
            "content_type": "full_text",
            "mission": self.extract_mission_from_path(file_path),
            "data_type": self.extract_data_type_from_path(file_path),
            "document_category": self.extract_document_category_from_filename(
                file_path.name
            ),
            "file_size": len(content),
            "processed_timestamp": datetime.now().isoformat(),
        }
        return self.chunk_text(content, metadata)
    
    def extract_mission_from_path(self, file_path: Path) -> str:
        """Extract mission name from file path"""
        path_str = str(file_path).lower()
        if 'apollo11' in path_str or 'apollo_11' in path_str:
            return 'apollo_11'
        elif 'apollo13' in path_str or 'apollo_13' in path_str:
            return 'apollo_13'
        elif 'challenger' in path_str:
            return 'challenger'
        else:
            return 'unknown'
    
    def extract_data_type_from_path(self, file_path: Path) -> str:
        """Extract data type from file path"""
        path_str = str(file_path).lower()
        if 'transcript' in path_str:
            return 'transcript'
        elif 'textract' in path_str:
            return 'textract_extracted'
        elif 'audio' in path_str:
            return 'audio_transcript'
        elif 'flight_plan' in path_str:
            return 'flight_plan'
        else:
            return 'document'
    
    def extract_document_category_from_filename(self, filename: str) -> str:
        """Extract document category from filename for better organization"""
        filename_lower = filename.lower()
        
        # Apollo transcript types
        if 'pao' in filename_lower:
            return 'public_affairs_officer'
        elif 'cm' in filename_lower:
            return 'command_module'
        elif 'tec' in filename_lower:
            return 'technical'
        elif 'flight_plan' in filename_lower:
            return 'flight_plan'
        
        # Challenger audio segments
        elif 'mission_audio' in filename_lower:
            return 'mission_audio'
        
        # NASA archive documents
        elif 'ntrs' in filename_lower:
            return 'nasa_archive'
        elif '19900066485' in filename_lower:
            return 'technical_report'
        elif '19710015566' in filename_lower:
            return 'mission_report'
        
        # General categories
        elif 'full_text' in filename_lower:
            return 'complete_document'
        else:
            return 'general_document'
    
    def scan_text_files_only(self, base_path: str) -> List[Path]:
        """
        Scan data directories for text files only (avoiding JSON duplicates)
        
        Args:
            base_path: Base directory path
            
        Returns:
            List of text file paths to process
        """
        _base_path: Path = Path(base_path)
        files_to_process: List[Path] = []
        data_roots = [_base_path]
        if _base_path.name.lower() == "data":
            data_roots.append(_base_path / "text")
        elif _base_path.name.lower() not in {"text"}:
            data_roots.append(_base_path / "data" / "text")

        for data_root in data_roots:
            for data_dir in ("apollo11", "apollo13", "challenger"):
                directory_path = data_root / data_dir
                if not directory_path.is_dir():
                    continue
                logger.info("Scanning directory: %s", directory_path)
                text_files = list(directory_path.glob("**/*.txt"))
                files_to_process.extend(text_files)
                logger.info(
                    "Found %s text files in %s", len(text_files), directory_path
                )
        
        # Filter out unwanted files
        filtered_files: List[Path] = []
        seen_paths: set[Path] = set()
        for file_path in files_to_process:
            # Skip system files and summaries
            if (file_path.name.startswith('.') or 
                'summary' in file_path.name.lower() or
                file_path.suffix.lower() != ".txt"):
                continue
            resolved_path = file_path.resolve()
            if resolved_path in seen_paths:
                continue
            seen_paths.add(resolved_path)
            filtered_files.append(file_path)
        
        logger.info(f"Total text files to process: {len(filtered_files)}")
        
        # Log file breakdown by mission
        mission_counts: Dict[str, int] = {}
        for file_path in filtered_files:
            mission = self.extract_mission_from_path(file_path)
            mission_counts[mission] = mission_counts.get(mission, 0) + 1
        
        logger.info("Files by mission:")
        for mission, count in mission_counts.items():
            logger.info(f"  {mission}: {count} files")
        
        return filtered_files
    
    def add_documents_to_collection(
        self,
        documents: List[Tuple[str, Metadata]],
        file_path: Path,
        batch_size: int = 50,
        update_mode: UpdateMode = "skip",
        progress_callback: Callable[[DocumentUpdateStats], None] | None = None,
    ) -> DocumentUpdateStats:
        """
        Add documents to ChromaDB collection in batches with update handling
        
        Args:
            documents: List of (text, metadata) tuples
            file_path: Path to the source file
            batch_size: Number of documents to process in each batch
            update_mode: How to handle existing documents:
                        'skip' - skip existing documents
                        'update' - update existing documents
                        'replace' - delete all existing documents from file and re-add
            
        Returns:
            Dictionary with counts of added, updated, and skipped documents
        """
        if update_mode not in {"skip", "update", "replace"}:
            raise ValueError("update_mode must be 'skip', 'update', or 'replace'")
        stats: DocumentUpdateStats = {"added": 0, "updated": 0, "skipped": 0}
        replaced_file_ids: Set[str] = (
            set(self.get_file_documents(file_path))
            if update_mode == "replace"
            else set()
        )
        if not documents:
            if replaced_file_ids:
                self.collection.delete(ids=sorted(replaced_file_ids))
            return stats

        pending_add: List[Tuple[str, str, Metadata, List[float]]] = []
        pending_update: List[Tuple[str, str, Metadata, List[float]]] = []

        for chunk_text, metadata in documents:
            document_id = self.generate_document_id(file_path, metadata)
            exists = self.check_document_exists(document_id)
            if exists and update_mode == "skip":
                stats["skipped"] += 1
                if progress_callback is not None:
                    progress_callback({"added": 0, "updated": 0, "skipped": 1})
                continue
            embedding = self.get_embedding(chunk_text)
            item = (document_id, chunk_text, metadata, embedding)
            if exists:
                pending_update.append(item)
            else:
                pending_add.append(item)

        for offset in range(0, max(len(pending_add), len(pending_update)), batch_size):
            additions = pending_add[offset : offset + batch_size]
            updates = pending_update[offset : offset + batch_size]
            if additions:
                self.collection.add(
                    ids=[item[0] for item in additions],
                    documents=[item[1] for item in additions],
                    metadatas=[item[2] for item in additions],
                    embeddings=[item[3] for item in additions],
                )
                stats["added"] += len(additions)
                if progress_callback is not None:
                    progress_callback(
                        {"added": len(additions), "updated": 0, "skipped": 0}
                    )
            if updates:
                self.collection.update(
                    ids=[item[0] for item in updates],
                    documents=[item[1] for item in updates],
                    metadatas=[item[2] for item in updates],
                    embeddings=[item[3] for item in updates],
                )
                stats["updated"] += len(updates)
                if progress_callback is not None:
                    progress_callback(
                        {"added": 0, "updated": len(updates), "skipped": 0}
                    )
        if replaced_file_ids:
            current_file_ids = {
                self.generate_document_id(file_path, metadata)
                for _, metadata in documents
            }
            stale_file_ids = replaced_file_ids - current_file_ids
            if stale_file_ids:
                self.collection.delete(ids=sorted(stale_file_ids))
        return stats
    
    def process_all_text_data(
        self, base_path: str, update_mode: UpdateMode = "skip"
    ) -> PipelineStats:
        """
        Process all text files and add to ChromaDB
        
        Args:
            base_path: Base directory containing data folders
            update_mode: How to handle existing documents:
                        'skip' - skip existing documents (default)
                        'update' - update existing documents
                        'replace' - delete all existing documents from file and re-add
            
        Returns:
            Statistics about processed files
        """
        if update_mode not in {"skip", "update", "replace"}:
            raise ValueError("update_mode must be 'skip', 'update', or 'replace'")

        stats: PipelineStats = {
            "files_processed": 0,
            "documents_added": 0,
            "documents_updated": 0,
            "documents_skipped": 0,
            "errors": 0,
            "total_chunks": 0,
            "missions": {},
        }
        file_paths = self.scan_text_files_only(base_path)
        total_files = len(file_paths)
        started_at = time.monotonic()
        completed_files = 0
        with tqdm(
            total=total_files,
            desc="Preparing files",
            unit="file",
            dynamic_ncols=True,
            bar_format=(
                "{l_bar}{bar}| {n_fmt}/{total_fmt} files "
                "[{elapsed}<{remaining}] {postfix}"
            ),
        ) as progress:
            for file_path in file_paths:
                progress.set_description(f"Reading/chunking: {file_path.name}")
                mission = self.extract_mission_from_path(file_path)
                mission_stats = stats["missions"].setdefault(
                    mission,
                    {
                        "files": 0,
                        "chunks": 0,
                        "added": 0,
                        "updated": 0,
                        "skipped": 0,
                    },
                )
                try:
                    documents = self.process_text_file(file_path)
                    stats["total_chunks"] += len(documents)
                    mission_stats["chunks"] += len(documents)

                    def record_document_updates(
                        result: DocumentUpdateStats,
                    ) -> None:
                        stats["documents_added"] += result["added"]
                        stats["documents_updated"] += result["updated"]
                        stats["documents_skipped"] += result["skipped"]
                        mission_stats["added"] += result["added"]
                        mission_stats["updated"] += result["updated"]
                        mission_stats["skipped"] += result["skipped"]

                    progress.set_description(f"Embedding/indexing: {file_path.name}")
                    self.add_documents_to_collection(
                        documents,
                        file_path,
                        update_mode=update_mode,
                        progress_callback=record_document_updates,
                    )
                except Exception:
                    logger.exception("Failed to process %s", file_path)
                    stats["errors"] += 1
                else:
                    stats["files_processed"] += 1
                    mission_stats["files"] += 1
                finally:
                    completed_files += 1
                    elapsed = time.monotonic() - started_at
                    progress.set_postfix_str(
                        f"files={completed_files}/{total_files}, "
                        f"chunks={stats['total_chunks']}, "
                        f"added={stats['documents_added']}, "
                        f"updated={stats['documents_updated']}, "
                        f"skipped={stats['documents_skipped']}, "
                        f"errors={stats['errors']}, "
                        f"avg/file={elapsed / completed_files:.1f}s",
                        refresh=False,
                    )
                    progress.update(1)
        return stats
    
    def get_collection_info(self) -> CollectionInfo:
        """Get information about the ChromaDB collection"""
        return {
            "collection_name": self.collection_name,
            "document_count": self.collection.count(),
            "metadata": self.collection.metadata or {},
        }
    
    def query_collection(
        self, query_text: str, n_results: int = 5
    ) -> RetrievalResult:
        """
        Query the collection for testing
        
        Args:
            query_text: Query text
            n_results: Number of results to return
            
        Returns:
            Query results
        """
        if (
            isinstance(n_results, bool)
            or not isinstance(n_results, int)
            or n_results <= 0
        ):
            raise ValueError("n_results must be a positive integer")
        embedding = self.get_embedding(query_text)
        return normalize_retrieval_result(
            self.collection.query(
                query_embeddings=[embedding],
                n_results=n_results,
                include=["documents", "metadatas", "distances"],
            )
        )
    
    def get_collection_stats(self) -> CollectionStats:
        """Get detailed statistics about the collection"""
        all_docs = self.collection.get(include=["metadatas"])
        metadatas = all_docs["metadatas"]
        if not metadatas:
            return {
                "total_documents": 0,
                "missions": {},
                "data_types": {},
                "document_categories": {},
                "file_types": {},
            }

        def count_metadata_values(key: str) -> Dict[str, int]:
            counts: Dict[str, int] = {}
            for metadata in metadatas:
                value = str(metadata.get(key, "unknown"))
                counts[value] = counts.get(value, 0) + 1
            return counts

        return {
            "total_documents": len(metadatas),
            "missions": count_metadata_values("mission"),
            "data_types": count_metadata_values("data_type"),
            "document_categories": count_metadata_values("document_category"),
            "file_types": count_metadata_values("file_type"),
        }

def main() -> None:
    """Main function"""
    parser = argparse.ArgumentParser(description='ChromaDB Embedding Pipeline for NASA Data')
    parser.add_argument('--data-path', default='.', help='Path to data directories')
    parser.add_argument('--openai-key', required=True, help='OpenAI API key')
    parser.add_argument('--openai-base-url', help='Base URL for the OpenAI-compatible API')
    parser.add_argument('--chroma-dir', default='./chroma_db_openai', help='ChromaDB persist directory')
    parser.add_argument('--collection-name', default='nasa_space_missions_text', help='Collection name')
    parser.add_argument(
        '--embedding-model',
        '--openai-embedding-model',
        dest='openai_embedding_model',
        default='text-embedding-3-small',
        help='OpenAI embedding model',
    )
    parser.add_argument('--chunk-size', type=int, default=500, help='Text chunk size')
    parser.add_argument('--chunk-overlap', type=int, default=100, help='Chunk overlap size')
    parser.add_argument('--batch-size', type=int, default=50, help='Batch size for processing')
    parser.add_argument('--update-mode', choices=['skip', 'update', 'replace'], default='skip',
                       help='How to handle existing documents: skip, update, or replace')
    parser.add_argument('--test-query', help='Test query after processing')
    parser.add_argument('--stats-only', action='store_true', help='Only show collection statistics')
    parser.add_argument('--delete-source', help='Delete all documents from a specific source pattern')
    
    args = parser.parse_args()
    
    # Initialize pipeline
    logger.info("Initializing ChromaDB Embedding Pipeline...")
    pipeline = ChromaEmbeddingPipelineTextOnly(
        openai_api_key=args.openai_key,
        openai_base_url=args.openai_base_url,
        chroma_persist_directory=args.chroma_dir,
        collection_name=args.collection_name,
        openai_embedding_model=args.openai_embedding_model,
        chunk_size=args.chunk_size,
        chunk_overlap=args.chunk_overlap
    )
    
    # Handle delete source operation
    if args.delete_source:
        deleted_count = pipeline.delete_documents_by_source(args.delete_source)
        logger.info(f"Deleted {deleted_count} documents matching source pattern: {args.delete_source}")
        return
    
    # If stats only, show collection statistics and exit
    if args.stats_only:
        logger.info("Collection Statistics:")
        stats = pipeline.get_collection_stats()
        for key, value in stats.items():
            logger.info(f"{key}: {value}")
        return
    
    # Process all data
    logger.info(f"Starting text data processing with update mode: {args.update_mode}")
    start_time = time.time()
    
    stats = pipeline.process_all_text_data(args.data_path, update_mode=args.update_mode)
    
    end_time = time.time()
    processing_time = end_time - start_time
    
    # Print results
    logger.info("=" * 60)
    logger.info("PROCESSING COMPLETE")
    logger.info("=" * 60)
    logger.info(f"Files processed: {stats['files_processed']}")
    logger.info(f"Total chunks created: {stats['total_chunks']}")
    logger.info(f"Documents added to collection: {stats['documents_added']}")
    logger.info(f"Documents updated in collection: {stats['documents_updated']}")
    logger.info(f"Documents skipped (already exist): {stats['documents_skipped']}")
    logger.info(f"Errors: {stats['errors']}")
    logger.info(f"Processing time: {processing_time:.2f} seconds")
    
    # Mission breakdown
    logger.info("\nMission breakdown:")
    for mission, mission_stats in stats['missions'].items():
        logger.info(f"  {mission}: {mission_stats['files']} files, {mission_stats['chunks']} chunks")
        logger.info(f"    Added: {mission_stats['added']}, Updated: {mission_stats['updated']}, Skipped: {mission_stats['skipped']}")
    
    # Collection info
    collection_info = pipeline.get_collection_info()
    logger.info(f"\nCollection: {collection_info.get('collection_name', 'N/A')}")
    logger.info(f"Total documents in collection: {collection_info.get('document_count', 'N/A')}")
    
    # Test query if provided
    if args.test_query:
        logger.info(f"\nTesting query: '{args.test_query}'")
        results = pipeline.query_collection(args.test_query)
        if results and 'documents' in results:
            logger.info(f"Found {len(results['documents'][0])} results:")
            for i, doc in enumerate(results['documents'][0][:3]):  # Show top 3
                logger.info(f"Result {i+1}: {f"{doc[:200]}..." if doc else 'None'}")
    
    logger.info("Pipeline completed successfully!")

if __name__ == "__main__":
    main()
